# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_id', models.CharField(db_index=True, max_length=256)),
                ('write_id', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('nickname', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(blank=True, max_length=64, null=True)),
                ('experience', models.IntegerField(blank=True, default=0, null=True)),
                ('level', models.IntegerField(blank=True, default=0, null=True)),
                ('vip_level', models.IntegerField(blank=True, default=0, null=True)),
                ('account_balance', models.FloatField(blank=True, default=0, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReaderAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_id', models.CharField(db_index=True, max_length=256)),
                ('attention_book', models.CharField(blank=True, max_length=1024, null=True)),
                ('attention_writer', models.CharField(blank=True, max_length=1024, null=True)),
                ('attention_group', models.CharField(blank=True, max_length=1024, null=True)),
                ('belong_fans', models.CharField(blank=True, max_length=256, null=True)),
                ('more_detail', django_mysql.models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
