# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='write_id',
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='readeradditional',
            name='reader_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
